version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/
hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/app-start.sh
      runas: root
      timeout: 60
