version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-ecs: circleci/aws-ecs@01.1.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          repo: "${AWS_REPO_NAME}"
          tag: "latest"
      - aws-ecs/run-task:
          requires:
            - aws-ecr/build-and-push-image
          cluster: 'CLUSTER_NAME'
          task-definition: ''
          awsvpc: false
          launch-type: EC2